cxx_binary(
  name = 'preprocess_pragma_output',
  header_namespace = '',
  headers = subdir_glob([
    ('', '**/*.h'),
  ]),
  srcs = glob([
    '**/*.cpp',
  ]),
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:boost-wave',
  ],
)
