cxx_binary(
  name = 'emit_custom_line_directives',
  header_namespace = '',
  headers = subdir_glob([
    ('', '**/*.hpp'),
  ]),
  srcs = glob([
    '**/*.cpp',
  ]),
  deps = [
    '//:boost-wave',
  ],
)
